In [3]:
import arviz as az 

jax_idata_5000 = az.from_netcdf("/users/azhan378/data/azhang/efficient-fpt/examples/results/sampler_jax_20260126-233203/idata_jax.nc") # took approximately 114 minutes
cython_idata_5000 = az.from_netcdf("/users/azhan378/data/azhang/efficient-fpt/examples/results/sampler_cython_20260126-235701/idata_cython.nc") # took approximately 71 minutes

In [2]:
az.summary(jax_idata_5000)

,mean,sd,hdi_3%,hdi_97%,mcse_mean,mcse_sd,ess_bulk,ess_tail,r_hat
eta,0.674,0.012,0.653,0.696,0.0,0.0,2202.0,1173.0,1.0
kappa,0.493,0.008,0.479,0.509,0.0,0.0,1926.0,1448.0,1.0
a,2.053,0.017,2.018,2.082,0.0,0.0,1833.0,1398.0,1.0
b_raw_jax,0.838,0.014,0.813,0.867,0.0,0.0,1858.0,1591.0,1.0
x0_raw_jax,0.452,0.003,0.446,0.458,0.0,0.0,2607.0,1458.0,1.0
b,0.297,0.007,0.284,0.310,0.0,0.0,1780.0,1656.0,1.0
x0,-0.196,0.014,-0.223,-0.172,0.0,0.0,2536.0,1518.0,1.0

In [4]:
az.summary(cython_idata_5000)

,mean,sd,hdi_3%,hdi_97%,mcse_mean,mcse_sd,ess_bulk,ess_tail,r_hat
eta,0.674,0.011,0.650,0.691,0.001,0.000,288.0,244.0,1.01
kappa,0.494,0.008,0.477,0.507,0.001,0.000,157.0,165.0,1.02
a,2.053,0.017,2.024,2.085,0.002,0.001,115.0,167.0,1.02
b_raw_cy,0.838,0.014,0.815,0.866,0.001,0.001,93.0,200.0,1.03
x0_raw_cy,0.452,0.003,0.447,0.459,0.000,0.000,286.0,281.0,1.02
b,0.297,0.007,0.286,0.311,0.001,0.000,82.0,154.0,1.03
x0,-0.196,0.014,-0.221,-0.171,0.001,0.001,271.0,260.0,1.02