In [1]:
import scipy.io 
import pandas as pd 

data_path = "/users/azhan378/data/azhang/efficient-fpt/data/GLAMdata_monkey.csv"
pandas_data_df = pd.read_csv(data_path)

In [3]:
pandas_data_df

,subject,trial,rt,choice,item_value_0,item_value_1,gaze_0,gaze_1,monk,session,totFix,correctProb
0,0,0,0.427829,1,2,5,0.000000,1.000000,claudio,c13aug18,1,-0.011270
1,0,1,0.548053,0,3,2,0.354538,0.645462,claudio,c13aug18,2,0.203824
2,0,2,0.480907,1,5,3,0.215705,0.784295,claudio,c13aug18,2,-0.937474
3,0,3,0.598620,0,2,2,0.598138,0.401862,claudio,c13aug18,2,0.517811
4,0,4,0.527576,0,4,2,0.523217,0.476783,claudio,c13aug18,3,0.062526
...,...,...,...,...,...,...,...,...,...,...,...,...
30041,1,14428,0.713350,0,3,3,0.562300,0.437700,kirby,k9aug16,3,0.532967
30042,1,14429,0.548896,0,5,3,0.647059,0.352941,kirby,k9aug16,3,0.076177
30043,1,14430,0.707233,0,5,3,0.639933,0.360067,kirby,k9aug16,2,0.076177
30044,1,14431,0.647123,0,3,3,0.512358,0.487642,kirby,k9aug16,2,0.532967
30045,1,14432,0.827002,1,1,2,0.363635,0.636365,kirby,k9aug16,3,-0.168114

In [2]:
# data given by Vincent 

monkey_data_1 = pd.read_csv("/users/azhan378/data/azhang/efficient-fpt/data/behav_subj1.csv")
monkey_data_2 = pd.read_csv("/users/azhan378/data/azhang/efficient-fpt/data/behav_subj2.csv")
monkey_data_3 = pd.read_csv("/users/azhan378/data/azhang/efficient-fpt/data/behav_subj3.csv")
monkey_data_1

,trialNum,firstVal,secondVal,firstIsChosen,decisionRT,firstFixLat,secondFixLat,thirdFixLat
0,6,1,3,0,0.827066,0.162,0.510,NaN
1,11,1,2,1,0.847049,0.164,0.372,0.616
2,18,1,5,0,0.897351,0.166,0.414,NaN
3,61,1,1,0,0.877376,0.163,0.415,NaN
4,62,1,5,0,0.937264,0.178,0.430,NaN
...,...,...,...,...,...,...,...,...
582,481,5,5,1,0.739332,0.213,0.441,0.617
583,494,5,2,1,0.807278,0.222,0.526,0.670
584,503,5,5,1,0.757297,0.184,0.452,0.632
585,518,5,3,1,0.687202,0.160,0.404,0.540
586,528,5,4,1,0.787275,0.195,0.467,0.671

In [4]:
monkey_data_2

,trialNum,firstVal,secondVal,firstIsChosen,decisionRT,firstFixLat,secondFixLat,thirdFixLat
0,10,1,5,0,0.727110,0.154,0.374,NaN
1,16,1,3,0,0.827561,0.259,0.495,NaN
2,33,1,3,0,0.796906,0.147,0.415,NaN
3,50,1,3,0,0.817211,0.147,0.403,NaN
4,57,1,4,0,0.787259,0.178,0.446,NaN
...,...,...,...,...,...,...,...,...
602,536,5,4,1,0.687310,0.159,0.423,0.623
603,542,5,3,1,0.727077,0.207,0.483,0.659
604,549,5,3,1,0.718524,0.189,0.433,0.601
605,596,5,2,1,0.697137,0.163,0.419,0.599
606,602,5,4,1,0.737211,0.151,0.423,0.623